Web client class
m20-sch57/TheTrueHat-test-client pull request #1
Opened 2020-05-31 15:05 UTC by lounres

Made class for web interactions. It consists of Socket and HTTP parts.

2020-06-02 10:38 UTC, alexdany657 commented on web_API.js
> +"use strict"
Мне кажется, что стоит добавить `#!/usr/bin/node` и сделать скрипт исполняемым

2020-06-05 14:35 UTC, lounres commented on web_API.js
> +"use strict"
Хорошо, `#!/usr/bin/node` добавлю. А вот с исполняемостью непонятно: он же вроде уже исполняемый...
![изображение](https://user-images.githubusercontent.com/43728100/83888651-d28f8780-a752-11ea-9752-7362562061bf.png)

2020-06-07 10:33 UTC, alexdany657 requested changes
А в остальном все ОК. (Я потестил)

2020-06-07 10:33 UTC, alexdany657 commented on web_API.js
> +        this.emit("",
Тут нехватает названия сигнала

2020-06-07 11:20 UTC, lounres commented on web_API.js
> +        this.emit("",
Исправил.

2020-06-07 11:20 UTC, lounres commented on web_API.js
> +        this.emit("",
Починил.

2020-06-07 11:21 UTC, alexdany657 approved these changes
OK

2020-06-07 11:22 UTC, merged